# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Tarea1SD.sala_pb2 as sala__pb2


class SalaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerSala = channel.unary_unary(
                '/sala.SalaService/ObtenerSala',
                request_serializer=sala__pb2.SolicitudSala.SerializeToString,
                response_deserializer=sala__pb2.RespuestaSala.FromString,
                )


class SalaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerSala(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerSala': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerSala,
                    request_deserializer=sala__pb2.SolicitudSala.FromString,
                    response_serializer=sala__pb2.RespuestaSala.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sala.SalaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SalaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerSala(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sala.SalaService/ObtenerSala',
            sala__pb2.SolicitudSala.SerializeToString,
            sala__pb2.RespuestaSala.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
